### ISSUE TITLE
Deadlock when using SemaphoreSlim

### ISSUE THREAD

**Issue by Karql** [microsoft/coyote#368] opened 2022-08-19 09:07 UTC
Hi!

At the begining I would like to thank you for the greate library 😉

After upgrading I have a problem with testing code that using `SemaphoreSlim`.

Scenario:
- there is a service with cache
- when cache is not set yet service calls repository to get items
- in service there is a lock that preventing call repository multiple times

I get a deadlock when I run tests for this service.

I have prepared simplified sample repostiory to show this error: https://github.com/Karql/CoyoteSemaphoreSlimDeadlockIssue

When I use `DumbLock` instead of `SemaphoreSlimLock` deadlock does not occurs.
![image](https://user-images.githubusercontent.com/173098/185586356-3a1fac20-a617-4f99-ae7d-4149b656dc8d.png)

In version `1.4.3` everything was ok (branch: `v143`).

Am I doing something wrong?

I attach also the code:
```c#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using System.Threading;
using Xunit.Abstractions;
using Microsoft.Coyote;
using Microsoft.Coyote.SystematicTesting;
using System.Linq;
using System.Runtime.CompilerServices;
using System.IO;

namespace CoyoteDeadlock;

public class Item
{
    public string Name { get; set; }
}

public interface ICache
{
    void Set(string key, object value);
    object Get(string key);
}

public interface ILock
{
    Task WaitAsync();
    void Release();
}

public interface IItemsRepository
{
    Task<IEnumerable<Item>> GetItemsAsync();
}

public interface IItemsService
{
    Task<IEnumerable<Item>> GetItemsAsync();
}

public class DumbCache: ICache
{
    private readonly Dictionary<string, object> _cache = new Dictionary<string, object>();

    public object Get(string key)
    {
        return _cache.TryGetValue(key, out object value) ? value : null;
    }

    public void Set(string key, object value)
    {
        _cache[key] = value;
    }
}

public class DumbRepo : IItemsRepository
{
    public async Task<IEnumerable<Item>> GetItemsAsync()
    {
        return await Task.Run(() => new[]
        {
            new Item { Name = "Item1"},
            new Item { Name = "Item2"}
        });
    }
}

public class DumbLock : ILock
{
    public int i = 0;

    public void Release()
    {
        i -= 1;
    }

    public async Task WaitAsync()
    {
        i += 1;

        while (true)
        {
            if (i == 1) return;
            await Task.Delay(5);
        }
    }
}
public class SemaphoreSlimLock : ILock
{
    private readonly SemaphoreSlim _semaphore = new SemaphoreSlim(1, 1);

    public void Release()
    {
        _semaphore.Release();
    }

    public Task WaitAsync()
    {
        return _semaphore.WaitAsync();
    }
}

public class ItemsService : IItemsService
{
    private const string CacheKey = "items";

    private readonly IItemsRepository _itemsRepository;
    private readonly ICache _cache;
    private readonly ILock _lock;

    public ItemsService(IItemsRepository itemsRepository, ICache cache, ILock lck)
    {
        _itemsRepository = itemsRepository ?? throw new ArgumentNullException(nameof(itemsRepository));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        _lock = lck ?? throw new ArgumentNullException(nameof(lck));
    }

    public async Task<IEnumerable<Item>> GetItemsAsync()
    {
        var items = _cache.Get(CacheKey);

        if (items != null)
        {
            return (IEnumerable<Item>)items;
        }

        await _lock.WaitAsync();
        try
        {
            items = _cache.Get(CacheKey);

            if (items != null)
            {
                return (IEnumerable<Item>)items;
            }

            items = await _itemsRepository.GetItemsAsync();
            _cache.Set(CacheKey, items);

            return (IEnumerable<Item>)items;
        }

        finally
        {
            _lock.Release();
        }        
    }
}

public class DeadlockTest
{
    private readonly ITestOutputHelper _output;

    public DeadlockTest(ITestOutputHelper output)
    {
        _output = output ?? throw new ArgumentNullException(nameof(output));
    }
   
    public static async Task TestMethod(IItemsRepository repo, ICache cache, ILock lck)
    {
        var service = new ItemsService(repo, cache, lck);

        var task1 = service.GetItemsAsync();
        var task2 = service.GetItemsAsync();

        var restults = await Task.WhenAll(task1, task2);

        // here assertions like checking is repo received only one call
    }

    [Fact]
    public static void TestWithSemaphoreSlimLock()
    {
        RunSystematicTest(() => TestMethod(new DumbRepo(), new DumbCache(), new SemaphoreSlimLock()));
    }

    [Fact]
    public static void TestWithDumbLock()
    {
        RunSystematicTest(() => TestMethod(new DumbRepo(), new DumbCache(), new DumbLock()));
    }

    private static void RunSystematicTest(Func<Task> test, [CallerMemberName] string testName = null)
    {
        var configuration = Configuration.Create()
            .WithTestingIterations(100)
            .WithVerbosityEnabled();

        var testingEngine = TestingEngine.Create(configuration, test);
        testingEngine.Run();

        if (testingEngine.TestReport.NumOfFoundBugs > 0)
        {
            var error = testingEngine.TestReport.BugReports.First();
            File.WriteAllText(testName + ".schedule", testingEngine.ReproducibleTrace);
            Assert.True(false, $"Found bug: {error}");
        }
    }
}
```

Best regards,
Mateusz

**Comment by pdeligia** [comment] 2022-08-19 14:19
Thanks for reporting this @Karql! We need to investigate why your code was working in 1.4.3 but not after upgrading (to the latest I assume?), but regarding the `SemaphoreSlimLock` type I believe I know what is going on.

The issue is that the type is not automatically rewritten today, we have an implementation that can be used during testing (see [SemaphoreSlim.cs](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Types/Threading/SemaphoreSlim.cs)), but this is from earlier Coyote days when we did not support `coyote rewrite` to automatically rewrite the DLLs and intercept types for controlled testing and asked folks to manually use these "drop-in-replacement" types. It seems we never added it to our [type rewriting pass](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Passes/Rewriting/Types/TypeRewritingPass.cs#L28) and I think that is why its deadlocking for you because the type is not intercepted during testing (normally Coyote would figure out when say a task is trying to acquire a lock that is already held, and schedule some other task in the meantime, else deadlocks).

We need to test a bit the semaphore [implementation](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Types/Threading/SemaphoreSlim.cs) and that it works fine with rewriting and will try push this in the next nuget release (hopefully in a week or so). In the meantime, maybe you can do a workaround if possible? (You could even temporarily try to use the above SemaphoreSlim type from the `Microsoft.Coyote.Test` nuget package, just no guarantee it will be bug-free until we look at this properly and add to rewriting, so it's completely up to you).

**Comment by pdeligia** [comment] 2022-08-19 14:20
Also forgot to say thanks for preparing a mini repro/repo, incredibly helpful!

**Comment by Karql** [comment] 2022-08-19 20:03
@pdeligia thank you for the response 👌

> We need to investigate why your code was working in 1.4.3 but not after upgrading (to the latest I assume?)

Deadlock occurs for versions `>= 1.5.3` (this is next version available in nuget after `1.4.3`. I have not checked for `1.5.0`, 1.5.1`, `1.5.2`) 

![image](https://user-images.githubusercontent.com/173098/185697431-86dd9235-fc2e-463a-80a3-e1cc4a0a7166.png)

>The issue is that the type is not automatically rewritten today, we have an implementation that can be used during testing (see [SemaphoreSlim.cs](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Types/Threading/SemaphoreSlim.cs)), but this is from earlier Coyote days when we did not support coyote rewrite to automatically rewrite the DLLs and intercept types for controlled testing and asked folks to manually use these "drop-in-replacement" types. It seems we never added it to our [type rewriting pass](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Passes/Rewriting/Types/TypeRewritingPass.cs#L28) and I think that is why its deadlocking for you because the type is not intercepted during testing (normally Coyote would figure out when say a task is trying to acquire a lock that is already held, and schedule some other task in the meantime, else deadlocks).

I have seen your comment https://github.com/microsoft/coyote/issues/163#issuecomment-824575460 before 😉

> We need to test a bit the semaphore [implementation](https://github.com/microsoft/coyote/blob/main/Source/Test/Rewriting/Types/Threading/SemaphoreSlim.cs) and that it works fine with rewriting and will try push this in the next nuget release (hopefully in a week or so).

I will looking forward a new release 😊

> Also forgot to say thanks for preparing a mini repro/repo, incredibly helpful!

No problem!

Have a great weekend!
Mateusz

**Comment by pdeligia** [comment] 2022-08-26 14:31
Just a quick update @Karql: we got the _sync_ version of the `SemaphoreSlim` working automatically with rewriting, but for the _async_ version (`WaitAsync`, like in your example) we need to add extra support inside the Coyote runtime to make sure that it does not lose the right "context" of who is holding the lock after the await continuation and spuriously deadlocking itself (so far, we have only been handling _sync_ locking operations that do not have to deal with this complexity). I am working on the design of this, so should hopefully have an update next week, stay tuned!

**Comment by pdeligia** [comment] 2022-09-01 00:21
Good news @Karql, we now support `SemaphoreSlim`, well in my branch 😉. Your test does not deadlock anymore!

Was a bit tricky due to the `WaitAsync` that I mentioned, but we got there (and also some internal runtime enhancements that will make supporting similar async APIs in the future much easier). Need to test it a bit more, merge and then prepare a release, stay tuned!

**Comment by pdeligia** [comment] 2022-09-13 20:06
Update: this is now merged @Karql, will be available in the next release, need to get in a few more items/fixes before that, but will try to get it out very soon. I will update and close this issue once the release is available!

**Comment by pdeligia** [comment] 2022-09-19 19:55
Closing this issue, support is available in [v1.6.0](https://www.nuget.org/packages/Microsoft.Coyote/1.6.0). But feel free to reopen if you face any more issues with this API!

**Closed by pdeligia** 2022-09-19 19:55 UTC
Labels: bug, area-binary-rewriting

**Comment by Karql** [comment] 2022-09-20 04:05
Great to hear it! 😁

Have a good day!
Mateusz

**Comment by hroe** [comment] 2022-09-20 06:42
thx @pdeligia, will give this a try!
