### ISSUE TITLE
How to use Coyote with .Net Core 3.1

### ISSUE THREAD

**Issue by rduser** [microsoft/coyote#177] opened 2021-05-27 22:47 UTC
I am trying to using Coyote with .Net Core 3.1 which our project uses. However, after I rewrite the assembly the test assembly cannot use it any more.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Foo.AzureClient' with identity 'Foo.AzureClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	azureclient.tests	

I did the rewrite using the following steps

1. dotnet tool install --global Microsoft.Coyote.CLI
2. .csproj Postbuild command "coyote rewrite $(TargetPath)"

This is using 1.2.7

**Comment by rduser** [comment] 2021-05-28 22:00
I was able to get around this by cloning the repo, adding conditional compile flag NETCOREAPP3_1 and then invoking the tool directly.

**Comment by pdeligia** [comment] 2021-06-01 22:27
Thanks for reporting this issue @rduser, I have not seen this happening myself before, and Coyote already works with .NET Core 3.1, so I am wondering if some weird dependency issue is happening here, which seems to be the case based on the `System.Runtime` version mismatch in your error before and after rewriting.

Honestly, it is hard to tell without having access to the csproj files that you are trying to rewrite. Is there some more information that you could provide to help us understand what might be causing this? Are you trying to rewrite a project file that directly references `System.Runtime`, or does it happen indirectly through another assembly that you are rewriting or referencing?

I am not 100% sure if this would work, but could you try passing the `DependencySearchPaths` option to `coyote rewrite` through the JSON rewriting configuration file (in case you don't use the JSON, you can see [here](https://microsoft.github.io/coyote/#get-started/using-coyote/#configuration)). For example:

```
{
  "AssembliesPath": "...",
  "DependencySearchPaths": "...",
  "Assemblies": [
    "foo.dll",
    "bar.dll"
  ]
}
```

Where the `DependencySearchPaths` has the paths to search for resolving dependencies, and you can point to the path to the correct `System.Runtime` assembly.

If the above doesn't work, what would be really helpful is if you can provide us with a minimal repro. You could create a dummy solution with some bare minimal code and project file(s), mimicking your rewriting setup, which gives the same error. If you then put it on a dummy GitHub repro and share with us, we can try reproduce and investigate the issue. Thanks!

**Comment by pdeligia** [comment] 2021-06-17 16:05
@rduser, I am closing this issue due to inactivity and as I have not seen this issue in other users that are on .NET Core 3.1. But please feel free to reopen and let us know if you are still facing issues!

**Closed by pdeligia** 2021-06-17 16:05 UTC
